/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author chandrakanth
 */
@Named(value = "user")
@SessionScoped
public class User implements Serializable {

    /**
     * Creates a new instance of User
     */
    public User() {
    }
    
    //Generated by Map
	private static Map<String,Object> Gender;
	static{
		Gender = new LinkedHashMap<String,Object>();
		Gender.put("Male", "Male"); //label, value
		Gender.put("Female", "Female");
		Gender.put("LGBTQ", "LGBTQ");
	}

	public Map<String,Object> getGenderValue() {
		return Gender;
	}
        
        //Generated by Map
	private static Map<String,Object> LanguageValue;
	static{
		LanguageValue = new LinkedHashMap<String,Object>();
		LanguageValue.put("English", "English"); //label, value
		LanguageValue.put("French", "French");
		LanguageValue.put("German", "German");
                LanguageValue.put("Telugu", "Telugu");
                LanguageValue.put("Spanish", "Spanish");
                LanguageValue.put("Arabic", "2020");
	}

	public Map<String,Object> getLanguageValue() {
		return LanguageValue;
	}
        
        private static Map<String,Object> OtherappsValue;
	static{
		LanguageValue = new LinkedHashMap<String,Object>();
		LanguageValue.put("Twitter", "Twitter"); //label, value
		LanguageValue.put("Facebook", "Facebook");
		LanguageValue.put("LinkedIn", "LinkedIn");
                LanguageValue.put("Instagram", "Instagram");
                LanguageValue.put("Snapchat", "Snapchat");
                LanguageValue.put("Whatsapp", "Whatsapp");
	}

	public Map<String,Object> getOtherappsValue() {
		return LanguageValue;
	}
        
}
